apiVersion: v1
kind: ConfigMap
metadata:
  name: sovereign-watch-redpanda-config
  namespace: sovereign-watch
data:
  redpanda.yaml: |
    redpanda:
      data_directory: /var/lib/redpanda/data
      seed_servers: []
      kafka_api:
        - address: 0.0.0.0
          port: 9092
      advertised_kafka_api:
        - address: sovereign-watch-redpanda
          port: 9092
      rpc_server:
        address: 0.0.0.0
        port: 33145
      advertised_rpc_api:
        address: sovereign-watch-redpanda
        port: 33145
      developer_mode: true
    pandaproxy:
      pandaproxy_api:
        - address: 0.0.0.0
          port: 8082
      advertised_pandaproxy_api:
        - address: sovereign-watch-redpanda
          port: 8082
    schema_registry:
      schema_registry_api:
        - address: 0.0.0.0
          port: 8081
    rpk:
      overprovisioned: true
      smp: 1
      memory: 1G
