apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-sovereign-watch
  namespace: sovereign-watch
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ${ARC_KEYVAULT_NAME}
    cloudName: "${ARC_CSI_CLOUD_NAME}"
    tenantId: ${ARC_TENANT_ID}
    objects: |
      array:
        - |
          objectName: sovereign-watch-pg-password
          objectType: secret
        - |
          objectName: sovereign-watch-entra-client-id
          objectType: secret
        - |
          objectName: sovereign-watch-entra-client-secret
          objectType: secret
        - |
          objectName: sovereign-watch-cookie-secret
          objectType: secret
        - |
          objectName: sovereign-watch-aisstream-api-key
          objectType: secret
  secretObjects:
    - secretName: sovereign-watch-secrets
      type: Opaque
      data:
        - objectName: sovereign-watch-pg-password
          key: POSTGRES_PASSWORD
    - secretName: sovereign-watch-entra
      type: Opaque
      data:
        - objectName: sovereign-watch-entra-client-id
          key: CLIENT_ID
        - objectName: sovereign-watch-entra-client-secret
          key: CLIENT_SECRET
        - objectName: sovereign-watch-cookie-secret
          key: COOKIE_SECRET
    - secretName: sovereign-watch-poller-secrets
      type: Opaque
      data:
        - objectName: sovereign-watch-aisstream-api-key
          key: AISSTREAM_API_KEY
