apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-deployment.yaml
  - db-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - cert-init-job.yaml
  - cert-export-job.yaml
