apiVersion: v1
kind: Service
metadata:
  name: takserver
  namespace: tak-server
  labels:
    app: takserver
spec:
  selector:
    app: takserver
  ports:
    - port: 8089
      targetPort: 8089
      name: tls
      protocol: TCP
    - port: 8443
      targetPort: 8443
      name: https
      protocol: TCP
    - port: 8444
      targetPort: 8444
      name: fed-https
      protocol: TCP
    - port: 8446
      targetPort: 8446
      name: cert-https
      protocol: TCP
    - port: 8088
      targetPort: 8088
      name: tcp
      protocol: TCP
    - port: 9000
      targetPort: 9000
      name: fed
      protocol: TCP
    - port: 9001
      targetPort: 9001
      name: fed2
      protocol: TCP
  type: NodePort
