---
# StorageClass: local-storage using no-provisioner
# PVs are defined alongside each app (e.g. windows-dc/, security-onion/).
# Host directories are created by rke2-arc-setup.sh on first boot.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
